import type { Candidate, JobRole, KanbanStatus } from './types';

export const KANBAN_COLUMNS: KanbanStatus[] = [
  'Uploaded',
  'Processing',
  'Screening',
  'Manual Review',
  'Interview',
  'Offer',
  'Hired',
  'Rejected',
  'Error'
];

export const mockCandidates: Candidate[] = [
  {
    id: 'cand-1',
    name: 'Priya Sharma',
    avatarUrl: 'https://placehold.co/100x100/4F46E5/FFFFFF',
    role: 'Senior Frontend Developer',
    skills: ['React', 'TypeScript', 'Next.js', 'GraphQL'],
    status: 'Interview',
    narrative: 'A seasoned frontend developer with 8 years of experience building scalable web applications. Passionate about user experience and design systems.',
    inferredSkills: ['State Management', 'Performance Optimization', 'CI/CD'],
    lastUpdated: '2 days ago',
  },
  {
    id: 'cand-2',
    name: 'Rohan Verma',
    avatarUrl: 'https://placehold.co/100x100/7C3AED/FFFFFF',
    role: 'Product Manager',
    skills: ['Agile', 'Roadmapping', 'User Research', 'JIRA'],
    status: 'Offer',
    narrative: 'Product manager with a track record of launching successful B2B SaaS products. Excels at cross-functional collaboration and data-driven decision making.',
    inferredSkills: ['Market Analysis', 'Stakeholder Management', 'Go-to-market Strategy'],
    lastUpdated: '1 day ago',
  },
  {
    id: 'cand-3',
    name: 'Anika Gupta',
    avatarUrl: 'https://placehold.co/100x100/E11D48/FFFFFF',
    role: 'Data Scientist',
    skills: ['Python', 'TensorFlow', 'PyTorch', 'SQL'],
    status: 'Hired',
    narrative: 'Data scientist specializing in natural language processing and machine learning models. Holds a Ph.D. in Computer Science.',
    inferredSkills: ['Statistical Analysis', 'Data Visualization', 'Big Data Technologies'],
    lastUpdated: '5 days ago',
  },
  {
    id: 'cand-4',
    name: 'Vikram Singh',
    avatarUrl: 'https://placehold.co/100x100/10B981/FFFFFF',
    role: 'DevOps Engineer',
    skills: ['AWS', 'Kubernetes', 'Terraform', 'Docker'],
    status: 'Screening',
    narrative: 'Certified AWS Solutions Architect with expertise in building and maintaining CI/CD pipelines for large-scale infrastructure.',
    inferredSkills: ['Infrastructure as Code', 'Monitoring & Alerting', 'Security Best Practices'],
    lastUpdated: '3 hours ago',
  },
  {
    id: 'cand-5',
    name: 'Sameera Khan',
    avatarUrl: 'https://placehold.co/100x100/F97316/FFFFFF',
    role: 'UX Designer',
    skills: ['Figma', 'Sketch', 'Prototyping', 'User Testing'],
    status: 'Manual Review',
    narrative: 'Creative UX designer focused on creating intuitive and user-centered designs. Experienced in both mobile and web application design.',
    inferredSkills: ['Wireframing', 'Interaction Design', 'Design Thinking'],
    lastUpdated: '1 day ago',
  },
  {
    id: 'cand-6',
    name: 'Arjun Reddy',
    avatarUrl: 'https://placehold.co/100x100/3B82F6/FFFFFF',
    role: 'Backend Developer',
    skills: ['Node.js', 'PostgreSQL', 'Microservices', 'REST APIs'],
    status: 'Uploaded',
    narrative: 'Backend developer with a passion for building robust and scalable systems. Strong understanding of database design and API architecture.',
    inferredSkills: ['System Design', 'Caching Strategies', 'Message Queues'],
    lastUpdated: 'Just now',
  },
    {
    id: 'cand-7',
    name: 'Neha Desai',
    avatarUrl: 'https://placehold.co/100x100/8B5CF6/FFFFFF',
    role: 'AI/ML Engineer',
    skills: ['Python', 'Scikit-learn', 'NLP', 'Computer Vision'],
    status: 'Interview',
    narrative: 'AI/ML engineer with experience in developing and deploying machine learning models in production environments. Keen interest in ethical AI.',
    inferredSkills: ['Model Optimization', 'Feature Engineering', 'Cloud ML Platforms'],
    lastUpdated: '3 days ago',
  },
  {
    id: 'cand-8',
    name: 'Karan Malhotra',
    avatarUrl: 'https://placehold.co/100x100/F43F5E/FFFFFF',
    role: 'Junior Frontend Developer',
    skills: ['JavaScript', 'HTML', 'CSS', 'React'],
    status: 'Rejected',
    narrative: 'Recent computer science graduate eager to apply my skills in a fast-paced environment. Strong foundation in web development fundamentals.',
    inferredSkills: ['Version Control (Git)', 'Responsive Design', 'API Consumption'],
    lastUpdated: '1 week ago',
  }
];

export const mockJobRoles: JobRole[] = [
  { id: 'role-1', title: 'Senior Frontend Developer', department: 'Engineering', openings: 2, description: "Looking for an experienced frontend developer to lead our web application development." },
  { id: 'role-2', title: 'Product Manager', department: 'Product', openings: 1, description: "Seeking a product manager to drive the vision and roadmap for our B2B SaaS product." },
  { id: 'role-3', title: 'Data Scientist', department: 'Data & Analytics', openings: 1, description: "Hiring a data scientist to build and deploy machine learning models." },
  { id: 'role-4', title: 'DevOps Engineer', department: 'Engineering', openings: 3, description: "We need a DevOps engineer to manage our cloud infrastructure and CI/CD pipelines." },
  { id: 'role-5', title: 'UX Designer', department: 'Design', openings: 1, description: "Creative UX designer needed to craft beautiful and intuitive user experiences." },
];
